### ISSUE TITLE
Mac OS X not working

### ISSUE THREAD

**Issue by bamundy** [mcanet/knitic#28]
I'm using a MacBookPro 2.7GHz Intel Core i7 8Gb 1333 MHz DDR3 RAM using OS X 10.9.5. with an Arduino compatible OSEPP Uno R3 Plus. 

I've downloaded the Arduino Application and am able to connect and power the board.

I've downloaded the latest Knitic software version from Github, yet every time I've attempted to open/install the software it gives the following error message . . . Please help.

Jo Ann Mundy

Arduino: 1.6.5 (Mac OS X), Board: "Arduino Uno"

protoAppKnitic_p5:11: error: variable or field 'serialEvent' declared void
protoAppKnitic_p5:11: error: expected ')' before 'p'
protoAppKnitic_p5:17: error: variable or field 'dropEvent' declared void
protoAppKnitic_p5:17: error: 'DropEvent' was not declared in this scope
protoAppKnitic_p5:8: error: 'import' does not name a type
protoAppKnitic_p5:9: error: 'import' does not name a type
protoAppKnitic_p5:10: error: 'import' does not name a type
protoAppKnitic_p5:11: error: 'import' does not name a type
protoAppKnitic_p5:12: error: 'import' does not name a type
protoAppKnitic_p5:13: error: 'import' does not name a type
protoAppKnitic_p5:17: error: 'ControlP5' does not name a type
protoAppKnitic_p5:18: error: 'Serial' does not name a type
protoAppKnitic_p5:19: error: 'PImage' does not name a type
protoAppKnitic_p5:20: error: 'PImage' does not name a type
protoAppKnitic_p5:21: error: 'PFont' does not name a type
protoAppKnitic_p5:29: error: expected unqualified-id before '[' token
protoAppKnitic_p5:39: error: expected unqualified-id before '[' token
protoAppKnitic_p5:40: error: expected unqualified-id before '[' token
protoAppKnitic_p5:70: error: storage size of 'bitRegister16SolenoidTemp' isn't known
protoAppKnitic_p5:71: error: 'SDrop' does not name a type
protoAppKnitic_p5:77: error: expected unqualified-id before '[' token
protoAppKnitic_p5:78: error: expected unqualified-id before '[' token
protoAppKnitic_p5:80: error: 'DropdownList' does not name a type
protoAppKnitic_p5:81: error: 'DropdownList' does not name a type
protoAppKnitic_p5:82: error: 'JSONObject' does not name a type
protoAppKnitic_p5:83: error: 'parametricSweater' does not name a type
protoAppKnitic_p5:84: error: 'controlP5' does not name a type
protoAppKnitic_p5:85: error: 'controlP5' does not name a type
protoAppKnitic_p5:86: error: 'controlP5' does not name a type
protoAppKnitic_p5:87: error: 'controlP5' does not name a type
protoAppKnitic_p5:88: error: 'controlP5' does not name a type
protoAppKnitic_p5:89: error: 'PFont' does not name a type
protoAppKnitic_p5:90: error: 'Boolean' does not name a type
protoAppKnitic_p5:92: error: 'controlP5' does not name a type
protoAppKnitic_p5:93: error: 'controlP5' does not name a type
protoAppKnitic_p5:94: error: 'controlP5' does not name a type
protoAppKnitic_p5:95: error: 'controlP5' does not name a type
protoAppKnitic_p5:96: error: 'controlP5' does not name a type
protoAppKnitic_p5.pde: In function 'void setup()':
protoAppKnitic_p5:100: error: 'P2D' was not declared in this scope
protoAppKnitic_p5:100: error: 'size' was not declared in this scope
protoAppKnitic_p5:101: error: 'noSmooth' was not declared in this scope
protoAppKnitic_p5:103: error: 'frame' was not declared in this scope
protoAppKnitic_p5:103: error: 'null' was not declared in this scope
protoAppKnitic_p5:106: error: 'ImageIcon' was not declared in this scope
protoAppKnitic_p5:106: error: expected ';' before 'titlebaricon'
protoAppKnitic_p5:107: error: 'titlebaricon' was not declared in this scope
protoAppKnitic_p5:110: error: 'setupSweater' was not declared in this scope
protoAppKnitic_p5:112: error: 'setupSettings' was not declared in this scope
protoAppKnitic_p5:113: error: 'addButtonsInSetup' was not declared in this scope
protoAppKnitic_p5:114: error: 'setupSerialConnection' was not declared in this scope
protoAppKnitic_p5:115: error: 'kniticLogo' was not declared in this scope
protoAppKnitic_p5:115: error: 'loadImage' was not declared in this scope
protoAppKnitic_p5:116: error: 'laurentFont' was not declared in this scope
protoAppKnitic_p5:116: error: 'loadFont' was not declared in this scope
protoAppKnitic_p5:117: error: 'currentPixels' was not declared in this scope
protoAppKnitic_p5:118: error: '_16SolenoidsAr' was not declared in this scope
protoAppKnitic_p5:121: error: 'setupAudio' was not declared in this scope
protoAppKnitic_p5:141: error: 'drop' was not declared in this scope
protoAppKnitic_p5:141: error: expected type-specifier before 'SDrop'
protoAppKnitic_p5:141: error: expected ';' before 'SDrop'
protoAppKnitic_p5:142: error: 'pixelSend' was not declared in this scope
protoAppKnitic_p5:143: error: 'pixelReceived' was not declared in this scope
protoAppKnitic_p5:148: error: 'createSweater' was not declared in this scope
protoAppKnitic_p5:149: error: 'showHideFeaturesOpenKnit' was not declared in this scope
protoAppKnitic_p5.pde: In function 'void draw()':
protoAppKnitic_p5:156: error: 'frame' was not declared in this scope
protoAppKnitic_p5:156: error: 'Integer' was not declared in this scope
In file included from protoAppKnitic_p5.pde:8:0:
protoAppKnitic_p5:156: error: 'frameRate' was not declared in this scope
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:88:24: note: in definition of macro 'round'
 #define round(x)     ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))
                        ^
protoAppKnitic_p5:157: error: 'background' was not declared in this scope
protoAppKnitic_p5:158: error: 'display' was not declared in this scope
protoAppKnitic_p5:159: error: 'drawPatternGrid' was not declared in this scope
protoAppKnitic_p5:162: error: 'drawPattern' was not declared in this scope
protoAppKnitic_p5:163: error: 'drawAndSetSelectedGrid' was not declared in this scope
protoAppKnitic_p5:166: error: 'showCursorPosition' was not declared in this scope
protoAppKnitic_p5:167: error: 'updateEditPixels' was not declared in this scope
protoAppKnitic_p5:169: error: 'drawReceivedPixelsVsSend' was not declared in this scope
protoAppKnitic_p5:172: error: 'machineList' was not declared in this scope
protoAppKnitic_p5:172: error: 'drawOpenKnit' was not declared in this scope
protoAppKnitic_p5:174: error: 'createSweater' was not declared in this scope
protoAppKnitic_p5:175: error: 'drawSweater' was not declared in this scope
protoAppKnitic_p5.pde: At global scope:
protoAppKnitic_p5:181: error: variable or field 'serialEvent' declared void
protoAppKnitic_p5:181: error: expected ')' before 'p'
protoAppKnitic_p5.pde: In function 'void brain()':
protoAppKnitic_p5:194: error: 'startRightSide' was not declared in this scope
protoAppKnitic_p5:195: error: 'startLeftSide' was not declared in this scope
protoAppKnitic_p5:209: error: 'done' was not declared in this scope
protoAppKnitic_p5:211: error: 'Integer' was not declared in this scope
protoAppKnitic_p5:211: error: 'println' was not declared in this scope
protoAppKnitic_p5:213: error: 'sendtoKnittingMachine' was not declared in this scope
protoAppKnitic_p5:226: error: 'done' was not declared in this scope
protoAppKnitic_p5:228: error: 'Integer' was not declared in this scope
protoAppKnitic_p5:228: error: 'println' was not declared in this scope
protoAppKnitic_p5:230: error: 'sendtoKnittingMachine' was not declared in this scope
protoAppKnitic_p5.pde: In function 'int getReadPixelsFromPosition(int)':
protoAppKnitic_p5:244: error: 'pixelArray' was not declared in this scope
protoAppKnitic_p5:246: error: expected type-specifier before 'Exception'
protoAppKnitic_p5:246: error: exception handling disabled, use -fexceptions to enable
protoAppKnitic_p5:246: error: expected ')' before 'e'
protoAppKnitic_p5:246: error: expected '{' before 'e'
protoAppKnitic_p5:246: error: 'e' was not declared in this scope
protoAppKnitic_p5:246: error: expected ';' before ')' token
protoAppKnitic_p5.pde: In function 'void setOFFSolenoids()':
protoAppKnitic_p5:256: error: '_16SolenoidsAr' was not declared in this scope
protoAppKnitic_p5.pde: At global scope:
protoAppKnitic_p5:274: error: variable or field 'dropEvent' declared void
protoAppKnitic_p5:274: error: 'DropEvent' was not declared in this scope
variable or field 'serialEvent' declared void

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by thiagohersan** [comment]
Hi. I'm just guessing, but it looks like you're trying to run the Processing code on the Arduino...

The stuff in the protoAppKnitic_p5 directory is an app for Processing. The Arduino code is in the directory called arduino_code/openKnitting_handMadepcb_v0_1.

**Comment by bamundy** [comment]
Thank you!!

jam
