### ISSUE TITLE
knitic page seems broken

### ISSUE THREAD

**Issue by Wouter1** [mcanet/knitic#37]
http://www.knitic.com/ seems broken

I only get a blank page (tested both on firefox and safari)

I was looking for info on how to use and attach this, why you need the PCB's provided here, some examples on what it can do, the supported hardware (I only see KH930 and KH940) etc. All this info seems not available here.

**Comment by ghost** [comment]
Still broken :/

**Comment by Kejkrt** [comment]
Arduino+shield --- [https://ayab-knitting.com/ayab-shield/](url)
