### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Josef-Reichardt** [mcanet/knitic#38]
I'm very interested building a knitting machine by my own and searching for some open source projects which I can use as a starting point or to find a community.

Can someone lead me to active projects for (open source) knitting machines? Im spacially interested in knitting motif socks.

**Comment by mcanet** [comment]
The project is not dead.

Latest iteration is a circular knitic machine that it is fully open
hardware and many people had replicate, and it is possible to extend
https://github.com/var-mar/circular_knitic
